---
title: "Spatially resticted genes"
author: "Sarah Williams"
output:
  html_notebook: 
    toc: yes
    code_folding: hide
  html_document:
    toc: yes
    df_print: paged
    code_folding: hide
editor_options:
  chunk_output_type: console
bibliography: /home/s.williams/zotero_export/MyLibrary.bib
---



## Using Seurat

Should wait for this bug to be fixed; logged here: https://github.com/satijalab/seurat/issues/8226

Maybe a fix?: https://github.com/satijalab/seurat/commit/038e98fc51369204ad4369e22337c176f1939dad#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231cR5



There's a workaround, but probably not suitable for this example doc.
Consider a voyager example or similar, that might be more suited to these kinds of ~very spatial~ analyses.


https://pachterlab.github.io/voyager/articles/vig4_cosmx.html#local-spatial-statistics-of-marker-genes




```{r angrylibrarian, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(echo = TRUE)
```

<!-- keywords

insituspatial
seurat
de
test

-->


### Load libraries and data

```{r}
library(Seurat)
library(tidyverse)
library(DT)

# Needed for moransI
#renv::install('Rfast2') # needs GSL installed on system
#renv::install('ape')

```

```{r}
dataset_dir      <- '~/projects/spatialsnippets/datasets/GSE263793_Mallach2024_AlzPlaque/processed_data/'
seurat_file_01_preprocessed <- file.path(dataset_dir,  "GSE263793_AlzPlaque_seurat_01_preprocessed.RDS")
```




```{r}
so <- readRDS(seurat_file_01_preprocessed)

# Tag fewer variable features
length(VariableFeatures(so))
so <-  FindVariableFeatures(so, nfeatures=10)

```





### Spatially variable features


```{r}
so.sample <- subset( so, cells = WhichCells(so, expression = sample == "sample1"))

so.sample.assay <- GetAssay(so.sample, assay = "RNA")
```

```{r}
renv::install("Rfast2")
```

```{r}
so.sample <- FindSpatiallyVariableFeatures(so.sample, 
                                           assay = "RNA", 
                                           features = VariableFeatures(so.sample),    
                                           selection.method = "moransi",
                                           layer = "counts")

```

```{r}

tc <- GetTissueCoordinates(object = so.sample[['AD2.AD3.CosMx']])

x <- FindSpatiallyVariableFeatures(so.sample.assay, 
                                  features = VariableFeatures(so.sample)[1:2],    
                                  spatial.location = tc,
                                  selection.method = "moransi",
                                  layer = "counts.AD2.AD3.CosMx")


x = FindSpatiallyVariableFeatures(so.sample.assay, 
                                  features = VariableFeatures(so.sample)[1:2],    
                                  spatial.location = tc,
                                  selection.method = "moransi",
                                  #layer = "counts.AD2.AD3.CosMx",
                                  slot='scale.data')
```




```{r}
  object = so.sample.assay
  slot = "scale.data"
  spatial.location = tc
  selection.method = 'moransi'
  #selection.method = c('markvariogram', 'moransi'),
  features = VariableFeatures(so.sample)[1:2]
  r.metric = 5
  x.cuts = NULL
  y.cuts = NULL
  nfeatures = 2
  verbose = TRUE

) {
  features <- features %||% rownames(x = object)
  if (selection.method == "markvariogram" && "markvariogram" %in% names(x = Misc(object = object))) {
    features.computed <- names(x = Misc(object = object, slot = "markvariogram"))
    features <- features[! features %in% features.computed]
  }
  data <- GetAssayData(object = object, slot = slot)
  data <- as.matrix(x = data[features, ])
  data <- data[Seurat:::RowVar(x = data) > 0, ]
  if (nrow(x = data) != 0) {
    svf.info <- FindSpatiallyVariableFeatures(
      object = data,
      spatial.location = spatial.location,
      selection.method = selection.method,
      r.metric = r.metric,
      x.cuts = x.cuts,
      y.cuts = y.cuts#,
      #verbose = verbose,
      #...
    )
  } else {
    svf.info <- c()
  }
  if (selection.method == "markvariogram") {
    if ("markvariogram" %in% names(x = Misc(object = object))) {
      svf.info <- c(svf.info, Misc(object = object, slot = "markvariogram"))
    }
    suppressWarnings(expr = Misc(object = object, slot = "markvariogram") <- svf.info)
    svf.info <- ComputeRMetric(mv = svf.info, r.metric)
    svf.info <- svf.info[order(svf.info[, 1]), , drop = FALSE]
  }
  if (selection.method == "moransi") {
    colnames(x = svf.info) <- paste0("MoransI_", colnames(x = svf.info))
    svf.info <- svf.info[order(svf.info[, 2], -abs(svf.info[, 1])), , drop = FALSE]
  }
  var.name <- paste0(selection.method, ".spatially.variable")
  var.name.rank <- paste0(var.name, ".rank")
  svf.info[[var.name]] <- FALSE
  svf.info[[var.name]][1:(min(nrow(x = svf.info), nfeatures))] <- TRUE
  svf.info[[var.name.rank]] <- 1:nrow(x = svf.info)
  object[[names(x = svf.info)]] <- svf.info
  return(object)
}
```





```{r}
source("code/spatially_variable_features_code.R")
so.sample <- FindSpatiallyVariableFeatures.Seurat_EDITED(so.sample, 
                                           assay = "RNA", 
                                           features = VariableFeatures(so.sample),    
                                           selection.method = "moransi",
                                           layer = "counts")

```





```{r}
# Can sorta get the top ones out.
rownames(so.sample[['RNA']])[which(so.sample[['RNA']]@meta.data$moransi.spatially.variable.rank <10)]

#gene_metadata <- cbind(feature=rownames(so.sample[["RNA"]]), so.sample[["RNA"]]@meta.data)
gene_metadata <- so.sample[["RNA"]]@meta.data
gene_metadata <- 
  filter(gene_metadata, !is.na(moransi.spatially.variable.rank)) %>%
  select(feature, 
         MoransI_observed, MoransI_p.value, moransi.spatially.variable,moransi.spatially.variable.rank) %>% 
  arrange(moransi.spatially.variable.rank)
  
                        
head(gene_metadata)
```




### plot it

Wow. Those top 3 are great.

```{r}
genes= gene_metadata$feature[1:3]

ImageDimPlot(so.sample,  fov = "AD2.AD3.CosMx",
             molecules = genes, 
             group.by = 'sample', boundaries = "segmentation",cols = c("grey30"),
             border.color = 'black', axes = T, crop=TRUE)


```





## Using Voyager


```{r}
#renv::install('bioc::Voyager')
library(Voyager)
```



```{r}
# CODE FROM 
# https://github.com/drighelli/SpatialExperiment/issues/115

library(SpatialExperiment)
library(Seurat)
#library(SeuratData)
# BiocManager::iBiocManager::install("SpatialExperiment")nstall("SpatialExperiment")
library(dplyr)

# SeuratData::InstallData(ds = "stxBrain")
#SeuratData::LoadData(ds = "tonsilref")
#se1 <- SeuratData::LoadData(ds = "stxBrain", type = "posterior1")
#se2 <- SeuratData::LoadData(ds = "stxBrain", type = "anterior1")

## Function
#seu <- so
#sample_id <- image
#img_id <- image



seurat_to_spe <- function(seu, sample_id, img_id) {
    ## Convert to SCE
    sce <- Seurat::as.SingleCellExperiment(seu)
    
    ## Extract spatial coordinates
    spatialCoords <- as.matrix(
        seu@images[[img_id]]@coordinates[, c("imagecol", "imagerow")])
    
    ## Extract and process image data
    img <- SpatialExperiment::SpatialImage(
        x = as.raster(seu@images[[img_id]]@image))
    
    imgData <- DataFrame(
        sample_id = sample_id,
        image_id = img_id,
        data = I(list(img)),
        scaleFactor = seu@images[[img_id]]@scale.factors$lowres)
    
    # Convert to SpatialExperiment
    spe <- SpatialExperiment(
        assays = assays(sce),
        rowData = rowData(sce),
        colData = colData(sce),
        metadata = metadata(sce),
        reducedDims = reducedDims(sce),
        altExps = altExps(sce),
        sample_id = sample_id,
        spatialCoords = spatialCoords,
        imgData = imgData
    )
    # indicate all spots are on the tissue
    spe$in_tissue <- 1
    spe$sample_id <- sample_id
    # Return Spatial Experiment object
    spe
}

#se_ls <- list("posterior1" = se1, "anterior1" = se2)
#spe_ls <- lapply(names(se_ls), function(i) {
#    seurat_to_spatialexperiment(seu = se_ls[[i]], sample_id = i, img_id = i)
#})
#
#spe <- Reduce(cbind, spe_ls)
#spe

```



```{r}
images <- Images(so)
image<- images[1]
#
#spe <- seurat_to_spe(seu = so, sample_id = image, img_id = image)
seu <- JoinLayers(so)

# remove niche assay.
seu[["niche"]]$data <- NULL
#seu[["niche"]]$counts <-NULL
seu[['niche']]<-NULL



# JUST convert RNA assay. Niche causes error.
sce <- Seurat::as.SingleCellExperiment(seu)

seurat_to_spe(seu, sample_id=image, img_id=image) 





```



```{r}


## Extract spatial coordinates
spatialCoords <- as.matrix(
        seu@images[[img_id]]@coordinates[, c("imagecol", "imagerow")])



#t. For spot-based data, assays contains a table named counts containing the gene counts, while for molecule-based data, assays may contain two tables named counts and molecules containing total gene counts per cell as well as molecule-level information such as spatial coordinates per molecule [formatted as a BumpyMatrix (Lun, 2021)]. 
#https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9154247/
  

molecules(seu) <- #XYZ.
```




