---
title: "Spatial omics analysis: Resources, Workshops and Vignettes"
output: html_notebook
---


Below are some tutorials and workshop materials for getting started in single-cell spatial analyses. These all cover QC and preprocessing in some form.




#### Spicy Workflow

[Spicy Workflow](https://bioconductor.org/packages/release/workflows/vignettes/spicyWorkflow/inst/doc/spicyWorkflow.html) 

An extensive vignette on single cell spatial omics analysis using the ['SCDNEY'](https://sydneybiox.github.io/scdney/) collection of bioconductor packages.
Covers the loading of image based data (of particular interest to protein imaging methods), through to QC and preprocessing and downstream analyses equally applicable to transcriptome based technologies.


#### Intro to spatial transcriptomics workshop material

[Intro to spatial transcriptomics](https://swbioinf.github.io/intro-spatial-transcriptomics-workshop/index.html)

Training materials for an introductory spatial transcriptomics workshop. This workshop demonstrates spatial pre-processing and QC steps in Seurat on the same [Garrido-Trigo et al. 2023](https://pubmed.ncbi.nlm.nih.gov/37495570/) IBD dataset used extensively within spatial sampler. It includes a section on how to practically tackle celltype annotation.


#### Voyager package documentation

[Voyager website](https://pachterlab.github.io/voyager/index.html) : Analysis vignettes are listed by technology for  for [Xenium](https://pachterlab.github.io/voyager/articles/xenium_landing.html), [cosmx](https://pachterlab.github.io/voyager/articles/cosmx_landing.html), [vizgen/merscope](https://pachterlab.github.io/voyager/articles/merfish_landing.html) and others.

Not a tutorial per se, but a collection of useful vignettes for loading, QC, processing and testing data using the voyager package. Part of the bioconductor ecosystem, voyager uses the 'SpatialFeatureExperiment' object that builds on 'SpatialExperiment'. Voyager functions focus on implementing spatial tests, and also provide some useful plotting functions.


#### OSTA (Orchestrating Spatial Transcriptomics Analysis with Bioconductor)

[OSTA (Orchestrating Spatial Transcriptomics Analysis with Bioconductor](https://lmweber.org/OSTA/)

A detailed resource on how to perform spatial analyses using the bioconductor ecosystem of packages. This is a useful resource for detailed explanations of analysis tasks.


_HL Crowell, Y Dong, I Billato, P Cai, M Emons, S Gunz, B Guo, M Li, A Mahmoud, A Manukyan, H Pagès, P Panwar, S Rao, CJ Sargeant, L Shepherd Kern, M Ramos, J Sun, M Totty, VJ Carey, Y Chen, L Collado-Torres, S Ghazanfar, KD Hansen, K Martinowich, KR Maynard, E Patrick, D Righelli, D Risso, S Tiberi, L Waldron, R Gottardo†°, MD Robinson, SC Hicks, LM Weber. Orchestrating spatial transcriptomics analysis with Bioconductor. bioRxiv (2025). DOI: 10.1101/2025.11.20.688607_


#### OSCA - (Orchestrating Single Cell Analayis with bioconductor 

[OSCA - (Orchestrating Single Cell Analayis with bioconductor )](https://bioconductor.org/books/release/OSCA/)

A detailed resource on single cell analyses using the bioconductor ecosystem of packages. Many of these tools and approaches can be directly applied to a spatial spatial analyses. 

_Amezquita, R.A., Lun, A.T.L., Becht, E. et al. Orchestrating single-cell analysis with Bioconductor. Nat Methods 17, 137–145 (2020). https://doi.org/10.1038/s41592-019-0654-x _

#### Seurat Imaging based spatial Vignette

[Seurat Imaging based spatial vignette](https://satijalab.org/seurat/articles/seurat5_spatial_vignette_2) 

The seurat vignette for spatial analysis, covering how to load data from a number of technologies. ( NB: See [ticket](https://github.com/satijalab/seurat/discussions/9261) for further info on cosmx data loading.)



#### Intermediate spatial 'taster' workshop

[Spatial taster workshop materials](https://github.com/swbioinf/spatial-taster-workshop/tree/main)

Training materials (Rmd files only) for an intermediate spatial transcriptomics workshop for comparative analyses using bioconductor packages. It again uses the the same [Garrido-Trigo et al. 2023](https://pubmed.ncbi.nlm.nih.gov/37495570/) IBD dataset used extensively within spatial sampler, and walks through differential expression by celltype, defining region niches and using those for differential expression by localisation, and celltype proximity tests.

#### Scverse python examples

[scverse getting started page](https://scverse.org/learn/)

This page links to many resources for using the python-based 'scverse' ecosystem.


#### 'Unlocking single cell spatial omics analysis with scdney' Workshop

[Unlocking single cell spatial omics analysis with scdney](https://sydneybiox.github.io/scdneySpatial_ABACBS2025/articles/workshop.html#overview)


Excellent workshop materials on single cell spatial omics analysis using the ['SCDNEY'](https://sydneybiox.github.io/scdney/) collection of bioconductor packages. Includes image analyse methods of particular interest to protein imaging methods, as well as methods equally applicable to transcriptome based technologies.

_Ameen F, Kim D, Rao S, Yu L, Patrick E, Yang J, Sydney Data Science Centre (2025). scdneySpatialABACBS2025: Unlocking single cell spatial omics analyses with scdney. R package version 0.1.0, https://sydneybiox.github.io/scdneySpatial_ABACBS2025/ _ 

<!--
Try out, link
https://github.com/bhuvad/CosMxSpatialAnalysisWorkshop/tree/main
-->
