---
title: "Data"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


Source of data.


<!-- * [Fuiten 2023 - Digits in a Dish](d_DigitsDish.html) : *Digits in a dish: An in vitro system to assess the molecular genetics of hand/foot development at single-cell resolution* Allison M. Fuiten, Yuki Yoshimoto, Chisa Shukunami, H. Scott Stadler. Fronteirs in Cell and Developmental Biology 2023. -->

These examples assume that the data has been loaded, preprocessed (e.g. QC-ed, UMAP) and annotated (e.g. sample names, cell types, cell niches). For information, the preprocessing applied here is included in data preparation below. Please note that these are not full annotations, and do not aim to reproduce the authors' published analyses! These are much simplified simply as a way to run these tests. 

* [IBD cosmx dataset](d_cosmxIBD.html) :  [_Macrophage and neutrophil heterogeneity at single-cell spatial resolution in human inflammatory bowel disease_](https://www.ncbi.nlm.nih.gov/pubmed/37495570) from Garrido-Trigo et al 2023.[@garrido-trigoMacrophageNeutrophilHeterogeneity2023] : This dataset includes cosmx samples across 9 individuals; 3 healthy, 3 with chrones disease and 3 with  Ulcerative colitis.
* [Alzheimers Plaques cosmx ](d_cosmxAlzPlaque.html): [Microglia-astrocyte crosstalk in the amyloid plaque niche of an Alzheimer’s disease mouse model, as revealed by spatial transcriptomics](https://www.sciencedirect.com/science/article/pii/S2211124724005448?via%3Dihub)
[@mallachMicrogliaastrocyteCrosstalkAmyloid2024]
* [Wnt4 KO in developing mouse kidney - 10X Chromium scRNAseq](d_Wnt4KO.Rmd): [Forming nephrons promote nephron progenitor maintenance and branching morphogenesis via paracrine BMP4 signalling under the control of Wnt4](https://www.biorxiv.org/content/10.1101/2023.11.19.567482v1.full) [@moreauFormingNephronsPromote2023a] : This dataset has 4 pools of single cell RNAseq data, total and conditional Wnt4 knockouts in E14.5 mouse kidney.

